on:
  push:
    branches:
      - m




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: 'before'
        run: ls


      - uses: actions/checkout@v3

      - name: 'after'
        run: ls

